// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cfpornasqnrrsflvtiay.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmcG9ybmFzcW5ycnNmbHZ0aWF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NDYwMjMsImV4cCI6MjA3MDAyMjAyM30.F-52c_zO7Il7-1KLMHYAFASTBwPEEEgZQFRI7SqZkas";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});